# Generated by Django 4.0.3 on 2022-03-21 04:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_alumni', models.BooleanField(default=False)),
                ('username', models.CharField(default=uuid.uuid1, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=60)),
                ('roll_number', models.CharField(max_length=9, unique=True)),
                ('list_of_comp', models.TextField(default='', verbose_name='List of Companies Applied')),
                ('SDprofile', models.BooleanField(default=True, verbose_name='SDE Profile Chosen')),
                ('DAprofile', models.BooleanField(default=False, verbose_name='DA Profile Chosen')),
                ('CV_SD', models.FileField(blank=True, default=None, null=True, upload_to='accounts/resumes', verbose_name='CV of Software Profile')),
                ('CV_DA', models.FileField(blank=True, default=None, null=True, upload_to='accounts/resumes', verbose_name='CV of Data Analytics Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=70, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=5, verbose_name='Select one Profile for which you want to recruit')),
                ('overview', models.TextField(default='', verbose_name='Company Overview(to display on Company Page)')),
                ('work_environ', models.TextField(default='', verbose_name='Work Environment')),
                ('job_desc', models.TextField(default='', verbose_name='Job Description')),
                ('other_details', models.TextField(default='', verbose_name='Some Other details(if any)')),
                ('verify_doc', models.FileField(blank=True, default=None, null=True, upload_to='accounts/company_req', verbose_name='Upload your Verification Documents(Single PDF)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=9, unique=True)),
                ('department', models.CharField(max_length=60)),
                ('year_of_graduation', models.IntegerField(default='2020', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
