# Generated by Django 4.0.3 on 2022-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='list_of_stud',
            field=models.TextField(default='', verbose_name='List of Student talked'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='list_of_stud_pend',
            field=models.TextField(default='', verbose_name='List of Student request pending'),
        ),
        migrations.AddField(
            model_name='company',
            name='list_of_students',
            field=models.TextField(default='', verbose_name='List of Students applied'),
        ),
        migrations.AddField(
            model_name='student',
            name='list_of_alum',
            field=models.TextField(default='', verbose_name='List of Alumni Talked'),
        ),
        migrations.AddField(
            model_name='student',
            name='list_of_alum_pend',
            field=models.TextField(default='', verbose_name='List of Alumni request pending'),
        ),
    ]
