# Generated by Django 4.0.3 on 2022-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chat_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='list_of_short_students',
            field=models.TextField(blank=True, default='', verbose_name='List of Students Shortlisted'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='year_of_graduation',
            field=models.IntegerField(default='2020'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
